### ISSUE TITLE
Change link in comment to point to actual TFC plan run

### ISSUE THREAD

**Issue by antonym** [hashicorp/tfc-workflows-gitlab#5]
Thanks for this, I was able to get it working.

On the comment put inside the MR, the Terraform Cloud Plan link links to $run_link (https://github.com/hashicorp/tfc-workflows-gitlab/blob/main/Base.gitlab-ci.yml#L111) which is a link to the MR the comment is posted in. Would it be possible to have this url link to the actual Terraform Cloud Plan that ran?

**Comment by zainq11** [comment]
Hello @antonym,
Thanks so much for spotting this. I have linked a PR to this issue. The PR has more details on the cause of this.
Basically, the `needs` keyword is not really required in this case because it limits the kind of variables that are available for adding to the comment body. These variables are exported by jobs from previous stages in the pipeline. You can also try this by removing this line from your [.gitlab-ci.yml](https://github.com/hashicorp/tfc-workflows-gitlab/blob/main/.gitlab-ci.yml#L89) file. This should allow `run_link` to be resolved.

Thanks so much for trying out our workflows-tooling.

**Comment by antonym** [comment]
Thanks! Validated this works and I now have a proper line to the plan!

**Comment by zainq11** [comment]
Thanks for the feedback and helping us test this out. We really appreciate it! 😃
